// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bimemrjjwnohxuufhijz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbWVtcmpqd25vaHh1dWZoaWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjc1MzksImV4cCI6MjA2MjY0MzUzOX0.QgHoWyTv0jMSzbW-eGjQZmDrMOLqQACLxmJKtQ2932U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);